install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages('plotrix')
install.packages('NbClust')
install.packages('factoextra')
